apiVersion: v1
kind: Template
labels:
  template: fom-public-build
  app: fom
  app-component: ${NAME}
  app.kubernetes.io/part-of: fom
metadata:
  name: fom-public-build
parameters:
  - description: Name of the application component
    displayName: Name
    name: NAME
    value: fom-public
  - description: Tag (e.g. release/build)
    displayName: Tag
    name: TAG
    value: demo
  - description: Git Source Reference (branch/tag/ref )
    displayName: Git Ref
    name: GIT_REF
    value: master
objects:
  ### ImageStream - scoped to entire application component, not to tag. Do not delete/recreate as this leads to loss of previously stored images
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  ### BuildConfig
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-${TAG}
      labels:
        tag: "${TAG}"
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      postCommit: {}
      source:
        type: Git
        git:
          uri: 'https://github.com/bcgov/nr-fom-public'
          ref: ${GIT_REF}
        contextDir: /
    runPolicy: SerialLatestOnly
#  triggers:
#    - type: Generic
#      generic:
#        secretReference:
#          name: nr-fom-admin-from-dockerfile-generic-webhook-secret
#    - type: GitHub
#      github:
#        secretReference:
#          name: nr-fom-admin-from-dockerfile-github-webhook-secret
#    - type: ConfigChange
